### ISSUE TITLE
Set Hastag Width

### ISSUE THREAD

**Issue by shahdivyank** [shahdivyank/beatdrop#343]
<img width="892" alt="image" src="https://user-images.githubusercontent.com/36285610/230552202-e4c3afab-1235-44fc-be9e-20e7ea134f32.png">

- Checkout the upload component and view component to see how this was done

**Comment by mgolwalla** [comment]
<img width="572" alt="image" src="https://user-images.githubusercontent.com/56405905/230704996-37badfc3-316b-412f-8460-36ce9721f78d.png">
