### ISSUE TITLE
Customize Fonts + Icons

### ISSUE THREAD

**Issue by shahdivyank** [shahdivyank/beatdrop#378]
![image](https://github.com/user-attachments/assets/bc9b65d3-9445-47bb-8dc4-4bd754c3953c)

- Icons for the tabs need to be imported/fixed
- fonts should be changed from the default to the one within figma 
- Either grab fonts from google fonts or place the font in assets
- Export icons from Figma
- Fix colors for the icons as well

**Comment by vraimondi04** [comment]
do you want it that the svg will change colors if the user is actively on that tab?
![image](https://github.com/user-attachments/assets/36ff5055-a79e-4dea-8f53-7a7d1443de65)

**Comment by shahdivyank** [comment]
Font finished, need to work on icons

**Comment by shahdivyank** [comment]
https://coolicons.cool this is where the icons are coming from, perhaps we can import an icon family and use that
