### ISSUE TITLE
Virtualize List

### ISSUE THREAD

**Issue by shahdivyank** [shahdivyank/beatdrop#382]
![image](https://github.com/user-attachments/assets/e90ba664-4f6f-46d1-9ddd-41683cb3c563)

- currently it is within a view component, it should be a scrollable component
- need to virtualize it as well for performance
- I would checkout tanstack virtual, there is also a virtualized list within the bottom sheet library itself
- Shopify also makes a fast list (I forgot the name) for RN and I would check that as well before deciding on one

**Comment by CarlMenke** [comment]
Yeah FlashList by Shopify would work great for this especially because all the items in the list are the same size
