### ISSUE TITLE
Add Camera Upload API

### ISSUE THREAD

**Issue by shahdivyank** [shahdivyank/beatdrop#385]
![image](https://github.com/user-attachments/assets/87d9a1d2-1328-4315-9a73-dfb4db0ac7c7)
![image](https://github.com/user-attachments/assets/5f5fcc8d-4dca-48d5-9b8e-8ef2e27b36e9)

- users need to be able to upload from their camera roll
- Users should be able to upload multiple pictures, for now set the maximum to 3 pictures
- Make sure it works out for both iOS and Android phones (API might be different across the 2 platforms)
- Do not worry about taking a current picture, only uploading, taking a picture will be apart of a separate issue

**Comment by CarlMenke** [comment]
going to use `expo-image-picker` for this
