### ISSUE TITLE
Image Compression

### ISSUE THREAD

**Issue by shahdivyank** [shahdivyank/beatdrop#404]
- Currently when an image is uploaded, it is most likely uploaded in full res, which is a huge file considering some pictures can be 15MB 
- Need to compress the images client side before sending them to the server

https://github.com/acm-ucr/hackathon-website/blob/dev/src/utils/convert.ts#L12
- compressor.js would work for web, not sure about native compatibility
- If expo has something in house, use that before reaching out to third party libraries

**Comment by CarlMenke** [comment]
Going to try and use [expo-image-manipulator](https://docs.expo.dev/versions/latest/sdk/imagemanipulator/)
